In [1]:
! pip install geocoder

Requirement already satisfied: geocoder in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (1.38.1)
Requirement already satisfied: six in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (from geocoder) (1.15.0)
Requirement already satisfied: future in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (from geocoder) (0.18.2)
Requirement already satisfied: click in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (from geocoder) (7.1.2)
Requirement already satisfied: requests in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (from geocoder) (2.24.0)
Requirement already satisfied: ratelim in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (from geocoder) (0.1.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (from requests->geocoder) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (from requests->geocoder) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (from requests->geocoder) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: decorator in /Users/florengutierrez/miniconda3/lib/python3.8/site-packages (from ratelim->geocoder) (4.4.2)

In [2]:
import geocoder
import requests
import pandas as pd
import numpy as np

In [3]:
dir(geocoder)

['__author__',
 '__author_email__',
 '__builtins__',
 '__cached__',
 '__copyright__',
 '__doc__',
 '__file__',
 '__license__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__title__',
 '__version__',
 'absolute_import',
 'api',
 'arcgis',
 'arcgis_reverse',
 'baidu',
 'baidu_reverse',
 'base',
 'bing',
 'bing_batch',
 'bing_batch_forward',
 'bing_batch_reverse',
 'bing_reverse',
 'canadapost',
 'cli',
 'distance',
 'elevation',
 'freegeoip',
 'gaode',
 'gaode_reverse',
 'geocodefarm',
 'geocodefarm_reverse',
 'geolytica',
 'geonames',
 'geonames_children',
 'geonames_details',
 'geonames_hierarchy',
 'get',
 'gisgraphy',
 'gisgraphy_reverse',
 'google',
 'google_elevation',
 'google_places',
 'google_reverse',
 'google_timezone',
 'here',
 'here_reverse',
 'ip',
 'ipinfo',
 'keys',
 'komoot',
 'komoot_reverse',
 'location',
 'locationiq',
 'locationiq_reverse',
 'mapbox',
 'mapbox_reverse',
 'mapquest',
 'mapquest_batch',
 'mapquest_reverse',
 'mapzen',
 'mapzen_reverse',
 'maxmind',
 'nokia',
 'opencage',
 'opencage_reverse',
 'osm',
 'osm_reverse',
 'ottawa',
 'places',
 'reverse',
 'tamu',
 'tgos',
 'timezone',
 'tomtom',
 'uscensus',
 'uscensus_batch',
 'uscensus_reverse',
 'w3w',
 'w3w_reverse',
 'yahoo',
 'yandex',
 'yandex_reverse']

In [4]:
geocoder.osm("San Cristóbal, Madrid").json

{'accuracy': 0.6324057754348258,
 'address': 'San Cristóbal, Villaverde, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España',
 'bbox': {'northeast': [40.350796, -3.6837459],
  'southwest': [40.3327234, -3.6930263]},
 'city': 'Madrid',
 'confidence': 7,
 'country': 'España',
 'country_code': 'es',
 'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png',
 'importance': 0.6324057754348258,
 'lat': 40.3433537,
 'lng': -3.6878175,
 'municipality': 'Área metropolitana de Madrid y Corredor del Henares',
 'ok': True,
 'osm_id': 9235995,
 'osm_type': 'relation',
 'place_id': 257942326,
 'place_rank': 20,
 'postal': '28001',
 'quality': 'administrative',
 'raw': {'place_id': 257942326,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 9235995,
  'boundingbox': ['40.3327234', '40.350796', '-3.6930263', '-3.6837459'],
  'lat': '40.3433537',
  'lon': '-3.6878175',
  'display_name': 'San Cristóbal, Villaverde, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España',
  'place_rank': 20,
  'category': 'boundary',
  'type': 'administrative',
  'importance': 0.6324057754348258,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png',
  'address': {'suburb': 'San Cristóbal',
   'city': 'Madrid',
   'municipality': 'Área metropolitana de Madrid y Corredor del Henares',
   'state': 'Comunidad de Madrid',
   'postcode': '28001',
   'country': 'España',
   'country_code': 'es'}},
 'region': 'Comunidad de Madrid',
 'state': 'Comunidad de Madrid',
 'status': 'OK',
 'suburb': 'San Cristóbal',
 'type': 'administrative'}

In [5]:
geocoder.osm("San Cristóbal, Madrid")

<[OK] Osm - Geocode [San Cristóbal, Villaverde, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España]>

---------

In [6]:
df2 = pd.read_csv("./data/inputs/houses_Madrid2.csv")

In [54]:
df2.shape

(16277, 18)

In [8]:
df2 = df2.drop(columns=['Unnamed: 0'])

In [9]:
df = df2[['subtitle']]
df

                                       subtitle
0                         San Cristóbal, Madrid
1                           Los Ángeles, Madrid
2                            San Andrés, Madrid
3                            San Andrés, Madrid
4                           Los Rosales, Madrid
...                                         ...
16272  Campo de las Naciones-Corralejos, Madrid
16273  Campo de las Naciones-Corralejos, Madrid
16274                           Barajas, Madrid
16275  Campo de las Naciones-Corralejos, Madrid
16276                          Imperial, Madrid

[16277 rows x 1 columns]

In [10]:
address = df.subtitle.unique()
address

array(['San Cristóbal, Madrid', 'Los Ángeles, Madrid',
       'San Andrés, Madrid', 'Los Rosales, Madrid', 'Butarque, Madrid',
       'Villaverde, Madrid', 'Ambroz, Madrid',
       'Casco Histórico de Vicálvaro, Madrid',
       'El Cañaveral - Los Berrocales, Madrid',
       'Valdebernardo - Valderribas, Madrid', 'Vicálvaro, Madrid',
       'Casco Histórico de Vallecas, Madrid',
       'Ensanche de Vallecas - La Gavia, Madrid', 'Santa Eugenia, Madrid',
       'Villa de Vallecas, Madrid', 'Orcasitas, Madrid',
       'San Fermín, Madrid', 'Pradolongo, Madrid', 'Zofío, Madrid',
       'Almendrales, Madrid', 'Moscardó, Madrid',
       '12 de Octubre-Orcasur, Madrid', 'Usera, Madrid',
       'Valdeacederas, Madrid', 'Berruguete, Madrid',
       'Cuatro Caminos, Madrid', 'Cuzco-Castillejos, Madrid',
       'Bellas Vistas, Madrid', 'Ventilla-Almenara, Madrid',
       'Tetuán, Madrid', 'Adelfas, Madrid', 'Ibiza, Madrid',
       'Pacífico, Madrid', 'Niño Jesús, Madrid', 'Jerónimos, Madrid',
       'Estrella, Madrid', 'Retiro, Madrid', 'Palomeras Bajas, Madrid',
       'San Diego, Madrid', 'Palomeras sureste, Madrid',
       'Entrevías, Madrid', 'Numancia, Madrid', 'Portazgo, Madrid',
       'Puente de Vallecas, Madrid', 'Aravaca, Madrid',
       'Argüelles, Madrid', 'Moncloa, Madrid',
       'Ciudad Universitaria, Madrid', 'Valdezarza, Madrid',
       'El Plantío, Madrid', 'Fontarrón, Madrid', 'Vinateros, Madrid',
       'Marroquina, Madrid', 'Media Legua, Madrid', 'Horcajo, Madrid',
       'Pavones, Madrid', 'Puerta del Ángel, Madrid',
       'Los Cármenes, Madrid', 'Aluche, Madrid', 'Águilas, Madrid',
       'Lucero, Madrid', 'Campamento, Madrid', 'Cuatro Vientos, Madrid',
       'Latina, Madrid', 'Valdemarín, Madrid', 'Casa de Campo, Madrid',
       'Las Tablas, Madrid', 'La Paz, Madrid', 'Montecarmelo, Madrid',
       'Peñagrande, Madrid', 'Fuencarral, Madrid',
       'Tres Olivos - Valverde, Madrid', 'Pilar, Madrid',
       'Mirasierra, Madrid', 'El Pardo, Madrid',
       'Arroyo del Fresno, Madrid', 'Fuentelarreina, Madrid',
       'Sanchinarro, Madrid', 'Conde Orgaz-Piovera, Madrid',
       'Hortaleza, Madrid', 'Palomas, Madrid',
       'Virgen del Cortijo - Manoteras, Madrid',
       'Valdebebas - Valdefuentes, Madrid', 'Pinar del Rey, Madrid',
       'Canillas, Madrid', 'Apóstol Santiago, Madrid', 'Almagro, Madrid',
       'Trafalgar, Madrid', 'Nuevos Ministerios-Ríos Rosas, Madrid',
       'Vallehermoso, Madrid', 'Gaztambide, Madrid', 'Arapiles, Madrid',
       'Chamberí, Madrid', 'Ventas, Madrid', 'Pueblo Nuevo, Madrid',
       'Atalaya, Madrid', 'Quintana, Madrid', 'San Juan Bautista, Madrid',
       'Costillares, Madrid', 'Concepción, Madrid', 'Colina, Madrid',
       'San Pascual, Madrid', 'Ciudad Lineal, Madrid',
       'Chamartín, Madrid', 'El Viso, Madrid', 'Nueva España, Madrid',
       'Bernabéu-Hispanoamérica, Madrid', 'Prosperidad, Madrid',
       'Castilla, Madrid', 'Ciudad Jardín, Madrid',
       'Lavapiés-Embajadores, Madrid', 'Opañel, Madrid',
       'Comillas, Madrid', 'Abrantes, Madrid', 'San Isidro, Madrid',
       'Puerta Bonita, Madrid', 'Vista Alegre, Madrid',
       'Pau de Carabanchel, Madrid', 'Buena Vista, Madrid',
       'Carabanchel, Madrid', 'Huertas-Cortes, Madrid',
       'Malasaña-Universidad, Madrid', 'Chueca-Justicia, Madrid',
       'Palacio, Madrid', 'Sol, Madrid', 'Centro, Madrid',
       'Barrio de Salamanca, Madrid', 'Goya, Madrid',
       'Guindalera, Madrid', 'Lista, Madrid', 'Castellana, Madrid',
       'Fuente del Berro, Madrid', 'Recoletos, Madrid',
       'Imperial, Madrid', 'Chopera, Madrid', 'Acacias, Madrid',
       'Delicias, Madrid', 'Palos de Moguer, Madrid', 'Legazpi, Madrid',
       'Arganzuela, Madrid', 'Casco Histórico de Barajas, Madrid',
       'Alameda de Osuna, Madrid',
       'Campo de las Naciones-Corralejos, Madrid', 'Timón, Madrid',
       'Barajas, Madrid'], dtype=object)

-------------

In [20]:
#Importing the required modules
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

geolocator = Nominatim(user_agent="my_request")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

In [45]:
address_df = pd.DataFrame({'add': address})
address_df['location'] = address_df['add'].apply(geocode)
address_df['Lat'] = address_df['location'].apply(lambda x: x.latitude if x else None)
address_df['Lon'] = address_df['location'].apply(lambda x: x.longitude if x else None)
 
address_df

,add,location,Lat,Lon
0,"San Cristóbal, Madrid","(San Cristóbal, Villaverde, Madrid, Área metro...",40.343354,-3.687817
1,"Los Ángeles, Madrid","(Los Ángeles, Villaverde, Madrid, Área metropo...",40.356222,-3.699639
2,"San Andrés, Madrid","(San Andrés, Centro - El Arroyo - La Fuente, F...",40.285117,-3.795549
3,"Los Rosales, Madrid","(Los Rosales, Villaverde, Madrid, Área metropo...",40.357195,-3.689448
4,"Butarque, Madrid","(Butarque, Villaverde, Madrid, Área metropolit...",40.336404,-3.674240
...,...,...,...,...
140,"Casco Histórico de Barajas, Madrid",None,NaN,NaN
141,"Alameda de Osuna, Madrid","(Alameda de Osuna, Calle de La Rioja, Barrio d...",40.457581,-3.587975
142,"Campo de las Naciones-Corralejos, Madrid",None,NaN,NaN
143,"Timón, Madrid","(Timón, 7, Calle de Gabino Jimeno, Moscardó, U...",40.386338,-3.706973
144,"Barajas, Madrid","(Barajas, Madrid, Área metropolitana de Madrid...",40.473318,-3.579845

In [48]:
address_df.to_csv('./data/inputs/address_test.csv')

------------

In [50]:
address = address.tolist()

In [56]:
#address.update({'El Cañaveral - Los Berrocales, Madrid': [40.650953, -4.0376634],
#                'Valdebernardo - Valderribas, Madrid': [40.3925808, -3.6099196],
#                'Los Cármenes, Madrid': [40.4009117, -3.7507486],
#                'Casco Histórico de Barajas, Madrid': [40.4464812, -3.6279521],
#                'Campo de las Naciones-Corralejos, Madrid': [40.143387, -3.7155827]})

In [40]:
address_df

,add,location,Lat,Lon
0,"San Cristóbal, Madrid","(San Cristóbal, Villaverde, Madrid, Área metro...",40.343354,-3.687817
1,"Los Ángeles, Madrid","(Los Ángeles, Villaverde, Madrid, Área metropo...",40.356222,-3.699639
2,"San Andrés, Madrid","(San Andrés, Centro - El Arroyo - La Fuente, F...",40.285117,-3.795549
3,"Los Rosales, Madrid","(Los Rosales, Villaverde, Madrid, Área metropo...",40.357195,-3.689448
4,"Butarque, Madrid","(Butarque, Villaverde, Madrid, Área metropolit...",40.336404,-3.674240
...,...,...,...,...
140,"Casco Histórico de Barajas, Madrid",None,NaN,NaN
141,"Alameda de Osuna, Madrid","(Alameda de Osuna, Calle de La Rioja, Barrio d...",40.457581,-3.587975
142,"Campo de las Naciones-Corralejos, Madrid",None,NaN,NaN
143,"Timón, Madrid","(Timón, 7, Calle de Gabino Jimeno, Moscardó, U...",40.386338,-3.706973
144,"Barajas, Madrid","(Barajas, Madrid, Área metropolitana de Madrid...",40.473318,-3.579845

In [ ]:
# geocoder.osm("los berrocales, Madrid").json lat: 40.650953,lng: -4.0376634
# geocoder.osm("Valderribas, Madrid").json lat:40.3925808, lng:-3.6099196
# geocoder.osm("los Carmenes, Madrid").json lat:40.4009117,lng:-3.7507486
# geocoder.osm("Barajas, Madrid").json lat: 40.4464812, lng: -3.6279521
# geocoder.osm("Corralejos, Madrid").json lat:40.143387, lng:-3.7155827

In [55]:
address_df.to_csv('./data/inputs/neighborhood_coordinates.csv')

In [13]:
from datetime import datetime         #función que recibe una dirección y hace la llamada la libreria geocoder para recibir un json con datos de esta dirección (lat, long, código postal,...)

def function_address(address):
    
    #start = datetime.now()
    try:
        response = geocoder.osm(address + ", Madrid").json
        
    except: response = None
        
    #print(datetime.now() - start)
    return response
function_address("Calle de Godella, 64")

{'accuracy': 0.51,
 'address': 'Calle de Godella, San Cristóbal, Villaverde, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España',
 'bbox': {'northeast': [40.3403113, -3.6869149],
  'southwest': [40.3399674, -3.6874438]},
 'city': 'Madrid',
 'confidence': 10,
 'country': 'España',
 'country_code': 'es',
 'importance': 0.51,
 'lat': 40.3399674,
 'lng': -3.6874365,
 'municipality': 'Área metropolitana de Madrid y Corredor del Henares',
 'ok': True,
 'osm_id': 28683460,
 'osm_type': 'way',
 'place_id': 96501270,
 'place_rank': 26,
 'postal': '28001',
 'quality': 'residential',
 'quarter': 'San Cristóbal',
 'raw': {'place_id': 96501270,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'way',
  'osm_id': 28683460,
  'boundingbox': ['40.3399674', '40.3403113', '-3.6874438', '-3.6869149'],
  'lat': '40.3399674',
  'lon': '-3.6874365',
  'display_name': 'Calle de Godella, San Cristóbal, Villaverde, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28001, España',
  'place_rank': 26,
  'category': 'highway',
  'type': 'residential',
  'importance': 0.51,
  'address': {'road': 'Calle de Godella',
   'quarter': 'San Cristóbal',
   'suburb': 'San Cristóbal',
   'city': 'Madrid',
   'municipality': 'Área metropolitana de Madrid y Corredor del Henares',
   'state': 'Comunidad de Madrid',
   'postcode': '28001',
   'country': 'España',
   'country_code': 'es'}},
 'region': 'Comunidad de Madrid',
 'state': 'Comunidad de Madrid',
 'status': 'OK',
 'street': 'Calle de Godella',
 'suburb': 'San Cristóbal',
 'type': 'residential'}

In [14]:
new_address = pd.DataFrame({'add': df2.raw_address})    #recibe todas las filas de la columna donde están las direcciones y devuelve localización.
new_address['location'] = new_address['add'].apply(function_address)

 
new_address

,add,location
0,"Calle de Godella, 64","{'accuracy': 0.51, 'address': 'Calle de Godell..."
1,Calle de la del Manojo de Rosas,"{'accuracy': 0.91, 'address': 'Calle de La del..."
2,"Calle del Talco, 68","{'accuracy': 0.5209999999999999, 'address': '6..."
3,Calle Pedro Jiménez,None
4,Carretera de Villaverde a Vallecas,"{'accuracy': 0.72, 'address': 'Carretera de Vi..."
...,...,...
16272,Calle Bahía de Almería,"{'accuracy': 0.32100000000000006, 'address': '..."
16273,Calle Bahía de Alicante,"{'accuracy': 0.31100000000000005, 'address': '..."
16274,Urb. Campo de las Naciones - Corralejos,None
16275,"Calle Burriana, 12",None
16276,"Calle San Epifanio, 9","{'accuracy': 0.51, 'address': 'Calle San Epifa..."

In [15]:
def coordinate(x,typ):    #Del json recibido separo longitud y latitud.
    try:
        return x[typ]
        
    except: return None

In [16]:
new_address["latitud"] = new_address.location.apply(coordinate, typ = "lat")
new_address["longitude"] = new_address.location.apply(coordinate, typ = "lng")
new_address

,add,location,latitud,longitude
0,"Calle de Godella, 64","{'accuracy': 0.51, 'address': 'Calle de Godell...",40.339967,-3.687437
1,Calle de la del Manojo de Rosas,"{'accuracy': 0.91, 'address': 'Calle de La del...",40.359340,-3.698374
2,"Calle del Talco, 68","{'accuracy': 0.5209999999999999, 'address': '6...",40.344630,-3.715191
3,Calle Pedro Jiménez,None,NaN,NaN
4,Carretera de Villaverde a Vallecas,"{'accuracy': 0.72, 'address': 'Carretera de Vi...",40.357722,-3.685029
...,...,...,...,...
16272,Calle Bahía de Almería,"{'accuracy': 0.32100000000000006, 'address': '...",37.358639,-2.263164
16273,Calle Bahía de Alicante,"{'accuracy': 0.31100000000000005, 'address': '...",38.504129,-0.231753
16274,Urb. Campo de las Naciones - Corralejos,None,NaN,NaN
16275,"Calle Burriana, 12",None,NaN,NaN
16276,"Calle San Epifanio, 9","{'accuracy': 0.51, 'address': 'Calle San Epifa...",40.401237,-3.719128

In [19]:
new_address.isnull().sum()

add             0
location     3753
latitud      3753
longitude    3753
dtype: int64

Me ha tardado unas 3 horas en sacar todos los datos, mejor prevenir y guardarlos en csv.

In [ ]:
new_address.to_csv('./data/inputs/coordinates.csv')